workflows:
  android-build:
    name: Android Build
    max_build_duration: 60

    environment:
      java: 17

    scripts:
      - name: Build Debug APK
        script: |
          sed -i 's/\r$//' gradlew
          bash ./gradlew assembleDebug --stacktrace

    artifacts:
      - app/build/outputs/**/*.apk